### ISSUE TITLE
求助url_lists文件

### ISSUE THREAD

**Issue by Anthony1013** [hquzhuguofeng/New-Pointer-Generator-Networks-for-Summarization#2]
### 文件名字为：url_list 这个文件提示找不到。请问您这里可以提供这个url_list文件吗？

谢谢！

**Comment by hquzhuguofeng** [comment]
链接：https://pan.baidu.com/s/1Z4O044sv-WjyotEqJw0dVA 
提取码：3zpq

**Comment by hquzhuguofeng** [comment]
链接：https://pan.baidu.com/s/1Z4O044sv-WjyotEqJw0dVA&nbsp;
提取码：3zpq





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hquzhuguofeng/New-Pointer-Generator-Networks-for-Summarization"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 下午3:37
收件人:&nbsp;"hquzhuguofeng/New-Pointer-Generator-Networks-for-Summarization"<New-Pointer-Generator-Networks-for-Summarization@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hquzhuguofeng/New-Pointer-Generator-Networks-for-Summarization] 求助url_lists文件 (#2)





 
文件名字为：url_list 这个文件提示找不到。请问您这里可以提供这个url_list文件吗？
 
谢谢！
